### ISSUE TITLE
Do we have 6 or 8 edge detection

### ISSUE THREAD

**Issue by sumit03111988** [sawankumarbundelkhandi/edge_detection#36] opened 2020-09-24 07:14 UTC
Your work is too good. Do we have 6 or 8 edge detection.?

Can you please guide me how I can achieve, also its not working accurately while scanning any paper or document.

How can I get the accurate auto edge detection while scanning any document.

**Comment by sawankumarbundelkhandi** [comment] 2020-09-24 07:30
duplicate of https://github.com/sawankumarbundelkhandi/edge_detection/issues/27

**Closed by sawankumarbundelkhandi** 2020-09-24 07:30 UTC
