### ISSUE TITLE
Xcode 15 - Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by harshparikhfb** [sawankumarbundelkhandi/edge_detection#154] opened 2023-10-05 07:15 UTC
Swift Compiler Error (Xcode): Stored properties cannot be marked unavailable with '@available'
/Users/harsh/GitLab/PDF%20Scanner%20V/pdf_scanner_converter/ios/Pods/WeScan/WeScan/ImageScannerController.swift:196:5
ImageScannerController.swift:196

Swift Compiler Error (Xcode): Stored properties cannot be marked unavailable with '@available'
/Users/harsh/GitLab/PDF%20Scanner%20V/pdf_scanner_converter/ios/Pods/WeScan/WeScan/ImageScannerController.swift:199:5
ImageScannerController.swift:199

Swift Compiler Error (Xcode): Stored properties cannot be marked unavailable with '@available'
/Users/harsh/GitLab/PDF%20Scanner%20V/pdf_scanner_converter/ios/Pods/WeScan/WeScan/ImageScannerController.swift:202:5
ImageScannerController.swift:202

**Comment by sawankumarbundelkhandi** [comment] 2023-10-05 09:38
Duplicate of https://github.com/sawankumarbundelkhandi/edge_detection/issues/151

This is fixed and you can use it directly from Github in pubspec like
edge_detection:
git: https://github.com/sawankumarbundelkhandi/edge_detection.git

I will release it on pub soon.

**Closed by sawankumarbundelkhandi** 2023-10-05 09:38 UTC

**Comment by sawankumarbundelkhandi** [comment] 2023-10-17 15:21
@harshparikhfb it's available now here - https://pub.dev/packages/edge_detection/versions/1.1.3
