### ISSUE TITLE
Edge detection is not working on ios xcode 15.0

### ISSUE THREAD

**Issue by dairy96** [sawankumarbundelkhandi/edge_detection#155] opened 2023-10-11 12:49 UTC
After adding the library to newly created project and when I try to run it on ios 
I have xcode 15.0 I'm getting this error

Swift Compiler Error (Xcode): Stored properties cannot be marked unavailable with '@available'
/Users/abdulmalekdery/tessafold/mobile/ios/Pods/WeScan/WeScan/ImageScannerController.swift:196:5

Swift Compiler Error (Xcode): Stored properties cannot be marked unavailable with '@available'
/Users/abdulmalekdery/tessafold/mobile/ios/Pods/WeScan/WeScan/ImageScannerController.swift:199:5

Swift Compiler Error (Xcode): Stored properties cannot be marked unavailable with '@available'
/Users/abdulmalekdery/tessafold/mobile/ios/Pods/WeScan/WeScan/ImageScannerController.swift:202:5

Swift Compiler Error (Xcode): Stored properties cannot be marked unavailable with '@available'
/Users/abdulmalekdery/tessafold/mobile/ios/Pods/WeScan/WeScan/ImageScannerController.swift:205:5

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

**Comment by sawankumarbundelkhandi** [comment] 2023-10-11 20:26
Duplicate of #151

This is fixed and you can use it directly from Github in pubspec like
edge_detection:
git: https://github.com/sawankumarbundelkhandi/edge_detection.git

make sure to add this step - https://github.com/sawankumarbundelkhandi/edge_detection?tab=readme-ov-file#fix-build-on-xcode-15

I will release it on pub later.

**Closed** 2023-10-11 20:26 UTC

**Comment by dairy96** [comment] 2023-10-12 23:53
why it was not uploaded ti pub dev yet?

**Comment by sawankumarbundelkhandi** [comment] 2023-10-17 15:20
@dairy96 it's available now here - https://pub.dev/packages/edge_detection/versions/1.1.3

**Comment by TheArchitect123** [comment] 2024-02-18 19:07
This issue unfornately is still there on v1.1.3
