### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libopencv_java3.so" not found

### ISSUE THREAD

**Issue by koitiyasojima-ufra** [sawankumarbundelkhandi/edge_detection#137] opened 2023-07-03 15:10 UTC
Trying to run the lastest version, im getting this error.
Any possible solution for this?

W/i.captura_prov(11828): Verification of void androidx.appcompat.app.AppCompatDelegateImpl.setOnBackInvokedDispatcher(android.window.OnBackInvokedDispatcher) took 174.880ms (285.91 bytecodes/s) (1480B approximate peak alloc)
D/AppCompatDelegate(11828): Checking for metadata for AppLocalesMetadataHolderService : Service not found
W/i.captura_prov(11828): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/i.captura_prov(11828): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/OpenCV/StaticHelper(11828): Trying to get library list
E/OpenCV/StaticHelper(11828): OpenCV error: Cannot load info library for OpenCV
D/OpenCV/StaticHelper(11828): Library list: ""
D/OpenCV/StaticHelper(11828): First attempt to load libs
D/OpenCV/StaticHelper(11828): Trying to init OpenCV libs
D/OpenCV/StaticHelper(11828): Trying to load library opencv_java3
D/OpenCV/StaticHelper(11828): Cannot load library "opencv_java3"
W/System.err(11828): java.lang.UnsatisfiedLinkError: dlopen failed: library "libopencv_java3.so" not found
W/System.err(11828): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
W/System.err(11828): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
W/System.err(11828): 	at java.lang.System.loadLibrary(System.java:1664)
W/System.err(11828): 	at org.opencv.android.StaticHelper.loadLibrary(StaticHelper.java:64)
W/System.err(11828): 	at org.opencv.android.StaticHelper.initOpenCVLibs(StaticHelper.java:95)
W/System.err(11828): 	at org.opencv.android.StaticHelper.initOpenCV(StaticHelper.java:39)
W/System.err(11828): 	at org.opencv.android.OpenCVLoader.initDebug(OpenCVLoader.java:102)
W/System.err(11828): 	at com.sample.edgedetection.scan.ScanActivity.prepare(ScanActivity.kt:41)
W/System.err(11828): 	at com.sample.edgedetection.base.BaseActivity.onCreate(BaseActivity.kt:20)
W/System.err(11828): 	at android.app.Activity.performCreate(Activity.java:8000)
W/System.err(11828): 	at android.app.Activity.performCreate(Activity.java:7984)
W/System.err(11828): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
W/System.err(11828): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
W/System.err(11828): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
W/System.err(11828): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
W/System.err(11828): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err(11828): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err(11828): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
W/System.err(11828): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(11828): 	at android.os.Looper.loop(Looper.java:223)
W/System.err(11828): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
W/System.err(11828): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(11828): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/System.err(11828): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
D/OpenCV/StaticHelper(11828): First attempt to load libs fails
I/ScanActivity(11828): loading opencv error, exit

**Comment by sawankumarbundelkhandi** [comment] 2023-07-04 11:37
duplicate of 
https://github.com/sawankumarbundelkhandi/edge_detection/issues/85
https://github.com/sawankumarbundelkhandi/edge_detection/issues/88

@koitiyasojima-ufra  can you please check it on another device as mentioned on https://github.com/sawankumarbundelkhandi/edge_detection/issues/88

**Comment by koitiyasojima-ufra** [comment] 2023-07-05 00:29
Thank you! ill try on a real device

**Comment by sawankumarbundelkhandi** [comment] 2023-07-05 15:43
@koitiyasojima-ufra please close it if it's workling.

**Closed** 2023-07-05 22:35 UTC
