### ISSUE TITLE
Please, update pub.dev

### ISSUE THREAD

**Issue by Zhanerkeb** [sawankumarbundelkhandi/edge_detection#62] opened 2021-10-15 06:23 UTC
Now the version in pub.dev has bugs according to FileNotFound exception and migration to Android V2

**Comment by sawankumarbundelkhandi** [comment] 2021-10-15 16:20
@Zhanerkeb I will publish it soon. I have 2 pending PR's to merge then I will release a new version.

Meanwhile, you can use it directly from Github like this

In pubspec, specify dependency like below

edge_detection:
    git:
      url: git://github.com/sawankumarbundelkhandi/edge_detection.git
  

Check git dependency section here for more information - https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

**Comment by Zhanerkeb** [comment] 2021-10-15 17:17
@sawankumarbundelkhandi I forked your repo, however it is too big. I have built apk, its size almost 120mb

**Comment by sawankumarbundelkhandi** [comment] 2021-10-16 08:08
@Zhanerkeb I will mark it as duplicate of https://github.com/sawankumarbundelkhandi/edge_detection/issues/51

**Closed by sawankumarbundelkhandi** 2021-10-16 08:08 UTC

**Comment by espbee** [comment] 2021-11-07 17:09
Hi @sawankumarbundelkhandi -- I appreciate the situation and don't mean to rush you. I'm trying to actually release a project soon. I don't mean to bug you at all, just trying to understand a timeline for when you may publish? I'd also be happy to help if you need anything--
