### ISSUE TITLE
ENOENT file not found error on Android 11 emulator

### ISSUE THREAD

**Issue by EdTengHR** [sawankumarbundelkhandi/edge_detection#50] opened 2021-06-09 05:44 UTC
Hi, when I run the example code on an emulator using Android 11, as soon as the save button is pressed, the app crashes, giving this error log:

E/CropActivity( 8333): Saved touched!
D/AndroidRuntime( 8333): Shutting down VM
E/AndroidRuntime( 8333): FATAL EXCEPTION: main
E/AndroidRuntime( 8333): Process: com.example.edge_detection_test, PID: 8333
E/AndroidRuntime( 8333): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 8333): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime( 8333): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 8333): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 8333): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8333): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 8333): 	... 1 more
E/AndroidRuntime( 8333): Caused by: java.io.FileNotFoundException: /storage/emulated/0/smart_scanner/crop_958.jpeg: open failed: ENOENT (No such file or directory)
E/AndroidRuntime( 8333): 	at libcore.io.IoBridge.open(IoBridge.java:492)
E/AndroidRuntime( 8333): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
E/AndroidRuntime( 8333): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
E/AndroidRuntime( 8333): 	at com.sample.edgedetection.crop.CropPresenter.save(CropPresenter.kt:217)
E/AndroidRuntime( 8333): 	at com.sample.edgedetection.crop.CropActivity.onOptionsItemSelected(CropActivity.kt:78)
E/AndroidRuntime( 8333): 	at android.app.Activity.onMenuItemSelected(Activity.java:4269)
E/AndroidRuntime( 8333): 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
E/AndroidRuntime( 8333): 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:196)
E/AndroidRuntime( 8333): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
E/AndroidRuntime( 8333): 	at androidx.appcompat.app.AppCompatDelegateImpl.onMenuItemSelected(AppCompatDelegateImpl.java:888)
E/AndroidRuntime( 8333): 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
E/AndroidRuntime( 8333): 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
E/AndroidRuntime( 8333): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
E/AndroidRuntime( 8333): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
E/AndroidRuntime( 8333): 	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
E/AndroidRuntime( 8333): 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
E/AndroidRuntime( 8333): 	at android.view.View.performClick(View.java:7448)
E/AndroidRuntime( 8333): 	at android.view.View.performClickInternal(View.java:7425)
E/AndroidRuntime( 8333): 	at android.view.View.access$3600(View.java:810)
E/AndroidRuntime( 8333): 	at android.view.View$PerformClick.run(View.java:28305)
E/AndroidRuntime( 8333): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 8333): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 8333): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 8333): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 8333): 	... 3 more
E/AndroidRuntime( 8333): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
E/AndroidRuntime( 8333): 	at libcore.io.Linux.open(Native Method)
E/AndroidRuntime( 8333): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
E/AndroidRuntime( 8333): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
E/AndroidRuntime( 8333): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
E/AndroidRuntime( 8333): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)
E/AndroidRuntime( 8333): 	at libcore.io.IoBridge.open(IoBridge.java:478)
E/AndroidRuntime( 8333): 	... 26 more
I/Process ( 8333): Sending signal. PID: 8333 SIG: 9

I've tried including: 
<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

in the AndroidManifest file, but that doesn't work either. 

Does anyone know where the issue lies and how I can fix this? Any help would be much appreciated.

**Comment by sawankumarbundelkhandi** [comment] 2021-06-09 10:45
@tengh1 can you check this issue? - https://github.com/sawankumarbundelkhandi/edge_detection/issues/33

**Comment by tengh1** [comment] 2021-06-10 06:51
> @tengh1 can you check this issue? - #33

I've checked it out, and that doesn't seem to be the cause of this problem. My API version, compileSDK and targetSDK versions are all 30. I think the problem may have something to do with scoped storage that Android 11 uses.

**Comment by tengh1** [comment] 2021-06-16 09:12
> > @tengh1 can you check this issue? - #33
> 
> I've checked it out, and that doesn't seem to be the cause of this problem. My API version, compileSDK and targetSDK versions are all 30. I think the problem may have something to do with scoped storage that Android 11 uses.

Tested with lower versions of Android emulator, and the plugin works, so I suppose it is an Android 11 problem...

**Comment by gamalielCastro** [comment] 2021-07-20 17:52
I have the same issue on andorid 11.
I have  investigated and seems to be that `android:requestLegacyExternalStorage="true"` now  is ignored.

[Here ](https://stackoverflow.com/questions/66642726/java-io-filenotfoundexception-open-failed-eexist-file-exists-android-11)more info.

**Comment by sawankumarbundelkhandi** [comment] 2021-10-02 15:08
@EdTengHR @gamalielCastro can you try again from the repo? I have merged the PR https://github.com/sawankumarbundelkhandi/edge_detection/pull/55 that fix the issue with scoped storage

**Closed by sawankumarbundelkhandi** 2021-10-02 15:08 UTC
