### ISSUE TITLE
how to get default number of  cropper edge point ?( for example 4 ).some time getting 3 edge point some time got 4 edge point ?

### ISSUE THREAD

**Issue by WafraRamees** [sawankumarbundelkhandi/edge_detection#156] opened 2023-10-17 10:45 UTC

**Comment by sawankumarbundelkhandi** [comment] 2023-10-17 15:25
duplicate of https://github.com/sawankumarbundelkhandi/edge_detection/issues/115

**Closed by sawankumarbundelkhandi** 2023-10-17 15:25 UTC
